version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13
        environment:
          MIX_ENV: test
      - image: circleci/mysql:8.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      # for debug
      - run: pwd
      - run:
          working_directory: app
          command: pwd
      - run: which mix
      - run: ls -alh
      - run:
          working_directory: app
          command: ls -alh

      - run:
          working_directory: app
          command: mix do deps.get, compile

