version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13
        environment:
          MIX_ENV: test
      - image: circleci/mysql:8.0

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      # for debug
      - run: pwd
      - run: which mix
      - run: ls -alh

      - run: mix do deps.get, compile

