version: 2.1

orbs:
  slack: circleci/slack@4.9.3
  terraform: circleci/terraform@3.0.1

jobs:
  terrafom_aws:
    working_directory: ~/repo
    steps:
      - checkout
      - run: env # for debug

      - terraform/fmt:
          workspace-root: ./infra/aws

      - terraform/validate:
          workspace-root: ./infra/aws

      - terraform/plan:
          workspace-root: ./infra/aws

      - slack/notify:
          event: always

  build:
    docker:
      - image: circleci/elixir:1.13-node
        environment:
          MIX_ENV: test
          MIX_TEST_DB_HOST: localhost
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root

    working_directory: ~/repo

    steps:
      - checkout
      - run: env # for debug

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run:
          working_directory: app
          command: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "app/mix.lock" }}
          paths: "app/deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "app/_build"

      - run:
          working_directory: app
          command: mix lint

      - run:
          working_directory: app
          command: mix test

      - slack/notify:
          event: always

workflows:
  test-and-deploy:
    jobs:
      - build:
          context: ohr486-circleci-notification
      - terraform_aws:
          context:
            - ohr486-circleci-notification
            - ohr486-aws-terraform
          
