version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13
        environment:
          MIX_ENV: test
      - image: circleci/mysql:8.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: env # for debug

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run:
          working_directory: app
          command: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "app/mix.lock" }}
          paths: "app/deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "app/_build"

      - run:
          working_directory: app
          command: mix test

